apiVersion: v2
name: @project.artifactId@
description: A Helm chart for Spring 6 Project
type: application
version: @helm.chart.version@
appVersion: @project.version@

dependencies:
  - name: kbe-brewery-beer-micro-service-mysql
    alias: mysql
    version: @helm.chart.version@
    repository: file://charts/mysql
    condition: mysql.enabled
  - name: kbe-brewery-beer-micro-service-jms
    alias: jms
    version: @helm.chart.version@
    repository: file://charts/jms
    condition: jms.enabled

