spring:
  application:
    name: kbe-brewery-beer-micro-service
  docker:
    compose:
      enabled: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: true
  cache:
    jcache:
      config: classpath:ehcache.xml
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    enabled: true
  cloud:
    discovery:
      enabled: false
  artemis:
    user: artemis
    password: simetraehcapa
  data:
    jpa:
      repositories:
        bootstrap-mode: default      

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  filter:
    enabled: true
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  predicate:
    exclude:
      - path: /actuator/health
        
sfg:
  brewery:
    beer-inventory-service-host: http://localhost:8082
    inventory-user: good
    inventory-password: beer

feign:
  client:
    config:
      default:
        logger-level: full        
