server:
  port: 8080

spring:
  application:
    name: kbe-brewery-beer-micro-service
    
  docker:
    compose:
      enabled: true
      stop:
        command: down
      
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: true
  cache:
    jcache:
      config: classpath:ehcache.xml

  zipkin:
    enabled: true
    
  cloud:
    discovery:
      enabled: false
      
  artemis:
    user: artemis
    password: simetraehcapa
    broker-url: tcp://localhost:61616
    
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/beerservice?useUnicode=yes&characterEncoding=UTF-8
      username: root
      password: dbpassword
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # Show SQL  
        show_sql: false
        # Format SQL
        format_sql: true
        
  data:
    jpa:
      repositories:
        bootstrap-mode: default      

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    access:
      default: unrestricted
    web:
      exposure:
        include: "*"
  endpoint:
    configprops:
      # WARNING: SECURITY RISK - DO NOT USE IN PRODUCTION ENVIRONMENT
      # This configuration exposes sensitive data and should only be used for development or testing purposes.
      # Ensure this is disabled in any environment where security is a concern.
      show-values: ALWAYS
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  filter:
    enabled: true
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  predicate:
    exclude:
      - path: /actuator/health
        
sfg:
  brewery:
    beer-inventory-service-host: http://localhost:8082
    inventory-user: good
    inventory-password: beer

feign:
  client:
    config:
      default:
        logger-level: full        
